### ISSUE TITLE
Refund me?

### ISSUE THREAD

**Issue by brendanhernou** [aviddot/Pancakeswap-and-uniswap-trading-bot#18]
Hey Aviddot,

on May 22nd, I sent you $300 for the paid version of the bot. After several days you told me that you would get back to me and send me multiple Aviddot tokens because I had to wait so much. It has been 18 days now and you have removed your Telegram account and haven't even tried to contact me back. Please refund me my money.

Tx hash of payment to your wallet: https://bscscan.com/tx/0xabcb1f914bbabcf785b02fc733b6e760c31a4ed949cf33132dc3be19b5d3f975

**Comment by brendanhernou** [comment]
Or at least contact me back on Telegram: @thecaptainhaze

**Comment by aviddot** [comment]
Please contact me on my email aviddotgithub@gmail.com

Btw: you are able to run the sniping bot you can download from the telegram channel (where also a guide is included)

**Comment by brendanhernou** [comment]
You never sent me any tokens, meaning I can't run the bot.

**Comment by aviddot** [comment]
> You never sent me any tokens, meaning I can't run the bot.

Oh I'm very sorry man, I was under the impression I had all that done.  The support got out of hand, with more new open chats coming then I could type. I also needed some time to work on other things in my life. Was a bit of a stressful decision...

Would you like the money back, or get multiple access tokens? I started working on the bot since today again. Either way, please message me with your decision

**Comment by brendanhernou** [comment]
I want my money back, you can send it to the same address as where I sent you 300 BUSD to.
